FROM python:3.10-slim

# Set the working directory to /app
WORKDIR /app

# Copy the project files to the container
COPY poetry.lock pyproject.toml /app/

ENV POETRY_VERSION=1.3.1
RUN pip install "poetry==$POETRY_VERSION" --no-cache-dir
RUN poetry config virtualenvs.create false

RUN poetry install --no-dev && yes | poetry cache clear . --all
COPY start.sh /app/
